### ISSUE TITLE
New Icon/New name

### ISSUE THREAD

**Issue by bertob** [Cogitri/Tau#252]
As we discussed on IRC last week, I'd be happy to make a new icon following the GNOME HIG for this app. I'm opening this issue to start brainstorming some potential metaphors.

Xi doesn't have a very distinctive logo, so I'm not sure there's much to go on from there.

![image](https://user-images.githubusercontent.com/1908896/58018612-936ca500-7b03-11e9-8358-e50fc4796ef2.png)

A few generic ideas for a text editor icon to start with:

- Pen and paper
- Keyboard
- Text Input Cursor
- Brackets (or other coding punctuation)

In general, there's the question of how closely this app wants to tie itself to the Xi brand. Perhaps we could first rename the app to something more distinctive, and then come up with an icon based on that?

**Comment by Cogitri** [comment]
> Perhaps we could first rename the app to something more distinctive, and then come up with an icon based on that?

That'd be nice, right now gxi isn't very searchable due to its name. I'm sort of bad at naming things though, maybe you already have something in mind?

**Comment by Cogitri** [comment]
> how closely this app wants to tie itself to the Xi brand

I think it's more of a question how closely gxi wants to be related to GNOME. I'd love to gxi to become a GNOMEy application, but I'm not quite sure what process to go through for that and I doubt gxi is up for GNOME's quality requirements as of right now (and there's already Gedit, I suppose).

**Comment by bertob** [comment]
Sorry for not following up, it's been in the back of my mind but I haven't gotten around to sitting down and thinking this through yet. Hopefully I will soon :)

In the meantime, you may be interested in this blog post https://blogs.gnome.org/tbernard/2019/04/26/naming-your-app/

**Comment by Cogitri** [comment]
Oh, no worries, thanks for your help! :)

I'll definitely check that out, naming things isn't exactly my strong point :P

**Comment by Cogitri** [comment]
Not quite sure if this fallsu under `Puns and inside jokes`, but maybe it'd be cool to call gxi like one of the letter of the Greek alphabet, like Xi?

Names of that I kind of like:

* Chi/Chei
* Tau (we could use a rope for the icon then, Tau is German for rope. Would also be kind of fitting since Xi's way to save lines (strings) is called `Rope`).
* Ny[lon]?

**Comment by Cogitri** [comment]
Or Leios? That means "smooth", apparently.

**Comment by little-dude** [comment]
Fwiw I like Tau.

**Comment by Cogitri** [comment]
Nice! I guess it's settled then, thank you :)

**Comment by bertob** [comment]
Greek letters sounds like a nice direction. No strong opinion on which one would be best, just make sure there's nobody else already using the name :)

**Comment by Cogitri** [comment]
Looks good in that regard. I guess I'll call the repository tau-editor for easier discoverability hough :)
