### ISSUE TITLE
In the about screen if you click close it does nothing.

### ISSUE THREAD

**Issue by Kommynct** [Cogitri/Tau#326]
## Expected Behavior
The close button should close the window

## Actual Behavior
Nothing happens

## Specifications

  - Version: 0.9.0
  - Platform: linux

**Comment by Cogitri** [comment]
Huh, seems to work for me:

![Peek 2019-06-20 12-49](https://user-images.githubusercontent.com/8766773/59843975-fdbe7280-9359-11e9-8c14-f1c7c94c2f65.gif)

Maybe you mean something else though?

**Comment by Kommynct** [comment]
Odd, yours looks extremely different from mine, i'm installing gxi-git from the aur.

![1561042651](https://user-images.githubusercontent.com/13646790/59859208-5259f180-934a-11e9-899c-f28fd201b679.png)

when i click close on the bottom it does nothing.

**Comment by Cogitri** [comment]
Ah, I just use the stock Adwaita theme. No worries about th theming thing, but I guess I should add a `What theme have you used/Can it be reproduced with Adwaita` to the issue report template. I guess I can look into this in a bit.

**Comment by Kommynct** [comment]
I think it has more to do with me using gtk3-mushrooms than my specific theme, so, perhaps add if you're using a fork of gtk? I'm not sure.

**Comment by Cogitri** [comment]
Oh, alright. I guess I'll close this now as this doesn't seem to be a bug of Tau but rather downstream oddness. Maybe you can ask them if they already experienced similiar problems.
