### ISSUE TITLE
View jumps when selecting with cursor on long line

### ISSUE THREAD

**Issue by macxcool** [Cogitri/Tau#347]
This happens when I scroll to the right on a long line and then start selecting text with shift and the left or right arrow key.

## Expected Behavior
Selection continues to the right or left as I hold down Shift and press the arrow key

## Actual Behavior
Selection does continue to the right or left as expected, but the view jumps back and forth between the left margin and the selection point on each press of the arrow key.

## Steps to Reproduce the Problem

  1. Create a long line of text that extends beyond the width of the screen
  2. Scroll to the right beyond the screen width and begin highlighting text using Shift and the left or right arrow keys
  3. The view will begin to jump back and forth with each press of the arrow key

## Specifications

  - Version: 0.11.3
  - Platform: Archlinux
  - Subsystem: i3 Window Manger

**Comment by Cogitri** [comment]
Heya,

Tau uses GNOME's gitlab for development now, sorry that that is not obvious from the GitHub page - I guess I should disable the issue/pull request pane on GitHub. I opened an issue for this on Gitlab some time ago: https://gitlab.gnome.org/World/Tau/-/issues/421. I hope I'll get to fixing that soon, but unfortunately I'll have to write exams soon, so it'll probably take me a bit to get to it. Thanks for reporting the issue and for the reproducer steps though, I'll add the details to the Gitlab issue.
